export const BREAKPOINT_SM_MIN = 576;
export const BREAKPOINT_MD_MIN = 768;
export const BREAKPOINT_LG_MIN = 992;
export const BREAKPOINT_XL_MIN = 1200;

export const BREAKPOINT_XS_MAX = BREAKPOINT_SM_MIN - 1;
export const BREAKPOINT_SM_MAX = BREAKPOINT_MD_MIN - 1;
export const BREAKPOINT_MD_MAX = BREAKPOINT_LG_MIN - 1;
export const BREAKPOINT_LG_MAX = BREAKPOINT_XL_MIN - 1;
