export type MarkName =
  | 'bold'
  | 'code'
  | 'italic'
  | 'link'
  | 'strike'
  | 'subscript'
  | 'superscript'
  | 'underline';

export type NodeName =
  | 'blockquote'
  | 'bulletList'
  | 'codeBlock'
  | 'color'
  | 'details'
  | 'detailsContent'
  | 'detailsSummary'
  | 'emoji'
  | 'document'
  | 'hardBreak'
  | 'heading'
  | 'horizontalRule'
  | 'image'
  | 'listItem'
  | 'mention'
  | 'orderedList'
  | 'paragraph'
  | 'table'
  | 'tableCell'
  | 'tableHeader'
  | 'tableRow'
  | 'taskItem'
  | 'taskList'
  | 'text'
  | 'youtube';
