version: 2.1

jobs:
  build:
    docker:
      - image: node:20-alpine
    steps:
      - checkout
      - run:
          name: Run Build and Tests
          command: |
            # Build and test commands go here

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
