import { describe, expect, it } from "vitest";

import { getOpenApiDocument } from "./openapi.js";

describe("getOpenApiDocument", () => {
  it("includes /api/health", () => {
    const doc = getOpenApiDocument();
    expect(doc.paths?.["/api/health"]?.get).toBeDefined();
  });

  it("includes session routes (Phase 3 contract)", () => {
    const doc = getOpenApiDocument();
    expect(doc.paths?.["/api/sessions/login"]?.post).toBeDefined();
    expect(doc.paths?.["/api/sessions/refresh"]?.post).toBeDefined();
    expect(doc.paths?.["/api/sessions/logout"]?.post).toBeDefined();
    expect(doc.paths?.["/api/sessions/demo"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/password"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/users/me/email-change"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/users/me/email-change/confirm"]?.post,
    ).toBeDefined();
    expect(doc.paths?.["/api/users"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/users/email-verification/resend"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/users/email-verification/confirm"]?.post,
    ).toBeDefined();
    expect(doc.paths?.["/api/users/me"]?.delete).toBeDefined();
    expect(
      doc.paths?.["/api/users/me/2fa/enable/request"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/users/me/2fa/enable/finish"]?.post,
    ).toBeDefined();
    expect(doc.paths?.["/api/users/me/2fa/load"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/users/me/2fa/recovery-codes"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/users/me/2fa/devices/forget"]?.post,
    ).toBeDefined();
    expect(doc.paths?.["/api/users/me/2fa/disable"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me/groups"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/starting"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/path"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/recent"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/recent/remove"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/recent/clear"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/favorites"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/favorites"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/favorites/remove"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me/pages/favorites/clear"]?.post).toBeDefined();
    expect(doc.paths?.["/api/users/me/defaults/note"]?.patch).toBeDefined();
    expect(doc.paths?.["/api/users/me/defaults/arrow"]?.patch).toBeDefined();
    expect(doc.paths?.["/api/users/me/notifications"]?.get).toBeDefined();
    expect(doc.paths?.["/api/users/me/notifications/read"]?.post).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/main-page"]?.get).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/members"]?.get).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/members/detail"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/invite-crypto-bootstrap"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/collab-crypto-context"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/privacy/make-private-bootstrap"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/public-keyring"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/users/{userId}/public-keyring"]?.get,
    ).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/pages"]?.get).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/pages"]?.post).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/password"]?.post).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/password"]?.patch).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/password"]?.delete).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/privacy/public"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/privacy/join-requests"]?.patch,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/privacy/private"]?.post,
    ).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}"]?.delete).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/restore"]?.post).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/purge"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-invitations"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-invitations/me/accept"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-invitations/me/reject"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-invitations/{userId}"]?.delete,
    ).toBeDefined();
    expect(doc.paths?.["/api/groups/{groupId}/join-requests"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-requests/me/cancel"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-requests/{userId}/accept"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/join-requests/{userId}/reject"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/members/{userId}"]?.patch,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/groups/{groupId}/members/{userId}"]?.delete,
    ).toBeDefined();
    expect(doc.paths?.["/api/pages/{pageId}/move"]?.post).toBeDefined();
    expect(doc.paths?.["/api/pages/{pageId}/bump"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/collab-updates"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/collab-updates"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/backlinks"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/backlinks/{targetPageId}"]?.delete,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/snapshots"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/snapshots"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/snapshots/{snapshotId}"]?.get,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/pages/{pageId}/snapshots/{snapshotId}"]?.delete,
    ).toBeDefined();
    expect(doc.paths?.["/api/pages/{pageId}"]?.delete).toBeDefined();
    expect(doc.paths?.["/api/pages/{pageId}/restore"]?.post).toBeDefined();
    expect(doc.paths?.["/api/pages/{pageId}/purge"]?.post).toBeDefined();
    expect(
      doc.paths?.["/api/billing/stripe/checkout-session"]?.post,
    ).toBeDefined();
    expect(
      doc.paths?.["/api/billing/stripe/portal-session"]?.post,
    ).toBeDefined();
    expect(doc.paths?.["/api/webhooks/stripe"]?.post).toBeDefined();
  });
});
