// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ColorPalette: typeof import('./src/components/ColorPalette.vue')['default']
    ColorSquare: typeof import('./src/components/ColorSquare.vue')['default']
    Combobox: typeof import('./src/components/Combobox.vue')['default']
    CopyBtn: typeof import('./src/components/CopyBtn.vue')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    DeepBtn: typeof import('./src/components/DeepBtn.vue')['default']
    DisplayBtn: typeof import('./src/components/DisplayBtn.vue')['default']
    EvaluatedPasswordField: typeof import('./src/components/EvaluatedPasswordField.vue')['default']
    Gap: typeof import('./src/components/Gap.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    MiniSidebarBtn: typeof import('./src/components/MiniSidebarBtn.vue')['default']
    PasswordDialog: typeof import('./src/components/PasswordDialog.vue')['default']
    PasswordField: typeof import('./src/components/PasswordField.vue')['default']
    QMenuHover: typeof import('./src/components/QMenuHover.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    ResponsiveContainer: typeof import('./src/components/ResponsiveContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCollapseBtn: typeof import('./src/components/SidebarCollapseBtn.vue')['default']
    SidebarPage: typeof import('./src/components/SidebarPage.vue')['default']
    TabBtn: typeof import('./src/components/TabBtn.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
    ToolbarBtn: typeof import('./src/components/ToolbarBtn.vue')['default']
    ViewportLoadingOverlay: typeof import('./src/components/ViewportLoadingOverlay.vue')['default']
  }
}
